name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  micro_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run micro test
        run: ./gradlew testDebug

  ui_test:
    runs-on: macOS-latest
    timeout-minutes: 60
    strategy:
      matrix:
        api-level: [ 29 ]
        target: [ default ]

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86
          emulator-build: 7425822
          script: ./gradlew connectedCheck --stacktrace

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Ui-Test-Reports
          path: app/build/reports
        if: always()
